### ISSUE TITLE
Bug in generate_conformers

### ISSUE THREAD

**Issue by PatWalters** [JoshuaMeyers/Snippets#1]
I think you have a bug the generate_conformers function
```
    for i in range(num_conf):
        temp_mol = Chem.Mol(mol_wh)  # copy to avoid inplace changes
        AllChem.ConstrainedEmbed(temp_mol, core1, randomseed=i)
#  Change the line below to assign the return value of RemoveHs like this
        temp_mol = Chem.RemoveHs(temp_mol)
# -----------------------------------------------
        conf_idx = outmol.AddConformer(temp_mol.GetConformer(0), assignId=True)
        if minimum_conf_rms is not None:
            if duplicate_conformers(outmol, conf_idx, rms_limit=minimum_conf_rms):
                dup_count += 1
                outmol.RemoveConformer(conf_idx)
```

**Comment by JoshuaMeyers** [comment]
Yep agreed, I often lose track of which functions edit inplace and which return a mol object.

Unfortunately, the suggested change causes an inconsistency since the mol object is expecting a conformer with more atoms. I will try to rework this in the next few days.

```
RuntimeError: Pre-condition Violation
	Number of atom mismatch
	Violation occurred on line 581 in file Code/GraphMol/ROMol.cpp
	Failed Expression: conf->getNumAtoms() == this->getNumAtoms()
	RDKIT: 2018.09.2
	BOOST: 1_67
```

**Comment by PatWalters** [comment]
Are you sure about this? I just ran this script on 832 molecules and it ran without a hitch. 

https://github.com/PatWalters/fragment_expansion/tree/master/rdkit_eval

**Comment by JoshuaMeyers** [comment]
Lovely to hear that it works 😄

I should have mentioned that the above error occurs if you run the mol object through the conformer generator twice which doesn't seem 'safe'. But I appreciate that you can definitely use it for most intensive purposes with the suggested change

**Comment by JoshuaMeyers** [comment]
I have reworked the function to remove an unnecessary duplicated mol object. And it now removes hydrogens as advertised. Cheers @PatWalters
